# Generated by Django 3.1.4 on 2020-12-23 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('repo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('repo_title', models.TextField()),
                ('repo_password', models.TextField()),
                ('repo_post_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('count', models.IntegerField()),
                ('repo_id', models.ForeignKey(db_column='repo_id', on_delete=django.db.models.deletion.CASCADE, to='app.repository')),
            ],
        ),
    ]
